In [4]:
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt

from imblearn.over_sampling import SMOTE

### prepare data

In [5]:
fpath = "/home/qian/UHstudy/ML/000project files/00Term project materials-20221204/npf_train.csv"
df = pd.read_csv(fpath)
df.head()
df.shape

(464, 104)

In [6]:
npf = df.copy()
class_type = np.array([0,1])
npf["class_type"] = class_type[(npf["class4"]!="nonevent").astype(int)]
npf.shape
npf["class_type"]

0      1
1      0
2      1
3      1
4      0
      ..
459    0
460    0
461    0
462    0
463    0
Name: class_type, Length: 464, dtype: int64

In [9]:
npf["multi_class"] = np.where(npf["class4"]=="nonevent",1,0)
npf["multi_class"] = np.where(npf["class4"]=="Ia",2,npf["multi_class"])
npf["multi_class"] = np.where(npf["class4"]=="Ib",3,npf["multi_class"])
npf["multi_class"] = np.where(npf["class4"]=="II",4,npf["multi_class"])
npf["multi_class"].value_counts()


1    232
4    113
3     85
2     34
Name: multi_class, dtype: int64

In [8]:
npf.head()

id        date    class4  partlybad  CO2168.mean  CO2168.std  CO2336.mean  \
0   1  2000-01-17        Ib      False   368.771711    0.310309   368.665658   
1   2  2000-02-28  nonevent      False   378.197295    1.001493   378.083089   
2   3  2000-03-24        Ib      False   373.043158    0.749865   372.930066   
3   4  2000-03-30        II      False   375.643019    0.558629   375.549430   
4   5  2000-04-04  nonevent      False   377.661030    0.408421   377.609576   

   CO2336.std  CO242.mean  CO242.std  ...  T84.mean   T84.std  UV_A.mean  \
0    0.305127  369.371184   0.333606  ... -0.899393  0.271648   2.492491   
1    1.025472  378.671311   1.017208  ...  2.033191  0.271090   0.295937   
2    0.728411  373.569735   0.835240  ...  0.780422  2.334741  14.434789   
3    0.540964  376.045849   0.580730  ...  6.533544  2.695277  16.077513   
4    0.423963  378.117134   0.417243  ...  2.133774  1.614122   9.710422   

   UV_A.std  UV_B.mean  UV_B.std   CS.mean    CS.std  class_type  multi_class  
0  1.310880   0.031587  0.018122  0.000243  0.000035           1            3  
1  0.177836   0.005140  0.003552  0.003658  0.000940           0            1  
2  8.627312   0.353743  0.272472  0.000591  0.000191           1            3  
3  9.984686   0.568242  0.451830  0.002493  0.000466           1            4  
4  7.054069   0.339135  0.291457  0.004715  0.000679           0            1  

[5 rows x 106 columns]

In [11]:
from sklearn.model_selection import train_test_split
X = npf.drop(["id","date","class4","partlybad","class_type","multi_class"],axis=1)

y = npf["multi_class"] 
y.value_counts()

# X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.5,random_state=101)
# y_train.value_counts()


1    232
4    113
3     85
2     34
Name: multi_class, dtype: int64

### Feature Selection

In [ ]:
# from sklearn.feature_selection import SelectFromModel
# from sklearn.linear_model import LogisticRegression
# # print(X.shape) 
# # X = SelectFromModel(LogisticRegression(penalty="none", C=0.2)).fit_transform(X, y)
# # print(X.shape) 
# print(X.shape)
# from sklearn.feature_selection import SelectKBest
# from sklearn.feature_selection import chi2
# from sklearn.svm import LinearSVC

# lsvc = LinearSVC(C=0.5, penalty="l2", dual=False).fit(X, y)
# model = SelectFromModel(lsvc, prefit=True)
# X = model.transform(X)
# print(X.shape)

### Standlization process

In [ ]:
#standardize the data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X = scaler.fit_transform(X)
# X_test = scaler.transform(X_test)
# X

### UP/DOWN sampling

In [12]:
_, X_test, _, y_test = train_test_split(X,y,test_size=0.3,random_state=101)

model_smote=SMOTE()
print(X.shape)
print(y.shape)
x_smote_resampled,y_smote_resampled=model_smote.fit_resample(X,y)  #Oversampling
y_smote_resampled.value_counts()


from imblearn.under_sampling import RandomUnderSampler #UnderSampler

model_RandomUnderSampler=RandomUnderSampler()   
x_RandomUnderSampler_resampled,y_RandomUnderSampler_resampled=model_RandomUnderSampler.fit_resample(X,y)  

# y_smote_resampled=pd.DataFrame(y_smote_resampled,columns=['label']) 
# smote_resampled=pd.concat([x_smote_resampled,y_smote_resampled],axis=1)  #rejoin features and labels
# group_data_smote=smote_resampled.groupby(['label'])['label'].count()   #check the amount
# x_smote_resampled 
# X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=101)
# y_train.value_counts()

X_train, _, y_train, _ = train_test_split(x_smote_resampled,y_smote_resampled,test_size=0.5,random_state=101)
y_train.value_counts()
# X_train, _, y_train, _ = train_test_split(x_RandomUnderSampler_resampled,y_RandomUnderSampler_resampled,test_size=0.5,random_state=101)
# y_train.value_counts()

(464, 100)
(464,)


2    130
4    113
1    112
3    109
Name: multi_class, dtype: int64

In [13]:
X_train.mean(axis=0)

CO2168.mean    380.469688
CO2168.std       2.661063
CO2336.mean    380.522197
CO2336.std       2.509072
CO242.mean     381.265757
                  ...    
UV_A.std         7.980268
UV_B.mean        0.461426
UV_B.std         0.386260
CS.mean          0.002466
CS.std           0.000572
Length: 100, dtype: float64

In [14]:
X_train.std(axis=0) 

CO2168.mean    9.311183
CO2168.std     2.704229
CO2336.mean    9.285499
CO2336.std     2.512657
CO242.mean     8.962828
                 ...   
UV_A.std       4.756510
UV_B.mean      0.304300
UV_B.std       0.274909
CS.mean        0.001723
CS.std         0.000514
Length: 100, dtype: float64

In [ ]:
# #PCA
# from sklearn.decomposition import PCA
# pca = PCA(n_components=2)
# X_train = pca.fit_transform(X_train)
# X_test = pca.transform(X_test)


In [15]:
#softmax regression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report
logmodel = LogisticRegression(multi_class="multinomial",solver="lbfgs")
logmodel.fit(X_train,y_train)
predictions = logmodel.predict(X_test)

print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))
#score
score = logmodel.score(X_test,y_test)
print("score",score)


[[51 10  3  8]
 [ 1  7  2  1]
 [ 3 11 17  0]
 [ 1  5  7 13]]
              precision    recall  f1-score   support

           1       0.91      0.71      0.80        72
           2       0.21      0.64      0.32        11
           3       0.59      0.55      0.57        31
           4       0.59      0.50      0.54        26

    accuracy                           0.63       140
   macro avg       0.57      0.60      0.56       140
weighted avg       0.72      0.63      0.66       140

score 0.6285714285714286


/home/qian/.local/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [16]:
print("predictions:",predictions)

predictions: [2 1 4 4 3 3 2 4 1 2 2 2 3 1 1 1 3 4 4 2 1 4 2 1 2 3 1 2 2 2 4 2 3 1 4 2 4
 4 4 4 1 2 1 1 1 2 4 4 2 1 2 3 1 1 1 1 1 1 1 2 2 1 2 4 3 3 3 1 4 1 2 3 1 1
 2 2 2 1 1 3 4 1 4 3 1 1 3 4 3 1 1 3 1 3 1 1 1 1 2 4 1 2 4 1 1 2 1 3 2 3 1
 3 3 3 3 1 2 1 3 1 1 2 3 1 3 1 1 3 2 1 2 3 1 2 1 1 1 4 3 1]


SVM

In [19]:
from sklearn.svm import SVC
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

clf = make_pipeline(StandardScaler(), SVC(gamma='auto'))
clf.fit(X_train,y_train)
predictions = clf.predict(X_test)

print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))
#score
score = clf.score(X_test,y_test)
print("score",score)


[[61  3  1  7]
 [ 0 11  0  0]
 [ 0  7 19  5]
 [ 4  2  2 18]]
              precision    recall  f1-score   support

           1       0.94      0.85      0.89        72
           2       0.48      1.00      0.65        11
           3       0.86      0.61      0.72        31
           4       0.60      0.69      0.64        26

    accuracy                           0.78       140
   macro avg       0.72      0.79      0.72       140
weighted avg       0.82      0.78      0.79       140

score 0.7785714285714286


Random Forest

In [18]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification


clf = RandomForestClassifier(max_depth=2, random_state=0) 
clf.fit(X_train,y_train)
predictions = clf.predict(X_test)

print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))
#score
score = clf.score(X_test,y_test)
print("score",score)

[[63  7  0  2]
 [ 0  9  1  1]
 [ 2  6 15  8]
 [ 3  8  3 12]]
              precision    recall  f1-score   support

           1       0.93      0.88      0.90        72
           2       0.30      0.82      0.44        11
           3       0.79      0.48      0.60        31
           4       0.52      0.46      0.49        26

    accuracy                           0.71       140
   macro avg       0.63      0.66      0.61       140
weighted avg       0.77      0.71      0.72       140

score 0.7071428571428572


### estimate answers

In [ ]:
npf_test = pd.read_csv('00Term project materials-20221204/npf_test_hidden.csv')
npf_test.head()

In [ ]:
npf_test.shape

In [ ]:
x_data = npf_test.drop(["id","date","class4","partlybad"],axis=1)
x_data.head()

In [ ]:
# x_data = scaler.transform(x_data)
# x_data.shape


In [ ]:
#estimate the probability of each class
y_prob = logmodel.predict_proba(x_data)
y_prob

In [ ]:
y_pred = logmodel.predict(X_train)

y_train[0:10]

In [ ]:
y_pred[0:10]

In [ ]:
y_prob[0:5]